pipacs/o2

- src/CMakeLists.txt
I recently tried building o2 using Qt5 and it seems to only need minor changes in the cmake file. I tried keeping compatibility with Qt4 by using the option WITH_QT5. If it isn't present all should compile as they do now, otherwise the appropriate options are set for the library to compile against Qt5.
> Support building with Qt5

- src/o1.cpp
Thank you for your cool library.
I've used o2 for tumblr but ``link`` function says:
``oauth_signature does not match expected value``
RequestTokenSecret is needed for exchanging  token.
So it should be stored before ``exchangeToken``.
> Store RequestTokenSecret for OAuth 1.0

- CMakeLists.txt
- examples/CMakeLists.txt
- examples/facebookdemo/CMakeLists.txt
- examples/twitterdemo/CMakeLists.txt
- src/CMakeLists.txt
This PR allows build options to be set via a CMake GUI frontend and provides a separate option for including generic OAuth1 code.
> Use CMake options for GUI frontend.

- src/o1.cpp
- src/o1.h
Query parameters must be signed -- they cannot simply be appended to the request token URL when it is set.
> Allow parameters (such as `scope`) to be passed with a token request.

- CMakeLists.txt
- src/o0baseauth.cpp
- src/o1.cpp
- src/o2.cpp
- src/o2facebook.cpp
- src/o2replyserver.cpp
- src/o2requestor.cpp
- src/o2skydrive.cpp
- src/oxtwitter.cpp
Here is another way to disable trace by default (instead of having it in the public API).
Thanks.
> Add `o2_SHOW_TRACE` option to enable trace output.

- src/o0baseauth.cpp
- src/o0baseauth.h
- src/o0settingsstore.cpp
- src/o0settingsstore.h
- src/o0simplecrypt.h
- src/o1.cpp
- src/o1.h
- src/o1requestor.h
- src/o1timedreply.cpp
- src/o1timedreply.h
- src/o2.cpp
- src/o2.h
- src/o2facebook.cpp
- src/o2facebook.h
- src/o2reply.cpp
- src/o2reply.h
- src/o2replyserver.cpp
- src/o2replyserver.h
- src/o2requestor.cpp
- src/o2requestor.h
- src/o2skydrive.cpp
- src/o2skydrive.h
- src/oxtwitter.cpp
- src/oxtwitter.h
Many projects build without Qt keywords enabled, so signals and slots are syntactically invalid. Also fix a compile error and warnings about a superfluous semicolon.
> Fixes for several compile warnings and errors - attempt 2

- src/o2.pri
It is more suitable to see 'o2' section in QtCreator instead 'src' section when a user adds .pri file to his project. It also maintains backwards compatibility with code that includes src.pri
> Add o2.pri

- CMakeLists.txt
- examples/CMakeLists.txt
- src/CMakeLists.txt
- src/o2spotify.cpp
- src/o2spotify.h
Hi there,
Thanks for building the lib.
Not sure if this is strictly required but I added a spotify subclass.
I also create a spotify example client, which is basically a copy of the FB example client. If you want it as well I can include it in this PR. (see https://github.com/lukedirtwalker/o2/tree/spotifyDemo)
Cheers
> Add spotify oauth classes

- CMakeLists.txt
- src/o0abstractstore.h
- src/o0baseauth.h
- src/o0export.h
- src/o0requestparameter.h
- src/o0settingsstore.h
- src/o0simplecrypt.h
- src/o1.h
- src/o1dropbox.h
- src/o1flickr.h
- src/o1freshbooks.h
- src/o1requestor.h
- src/o1timedreply.h
- src/o1twitter.h
- src/o2.h
- src/o2facebook.h
- src/o2gft.h
- src/o2hubic.h
- src/o2reply.h
- src/o2replyserver.h
- src/o2requestor.h
- src/o2skydrive.h
- src/o2surveymonkey.h
- src/oxtwitter.h
This is needed to create and link to an `o2` DLL under Windows. I wasn't sure what to call the define -- I decided to use `O0_EXPORT`, defined in `o0export.h`, and controlled by an `O2_EXPORT` compiler definition.
> Define and use DLL export/import declarations when building under Windows

- o2.pc.cmake
- src/CMakeLists.txt
Why?
> Without a metadata system such as pkg-config, it can be very difficult to locate and obtain details about the services provided on a given computer. For a developer, installing pkg-config files with your package greatly eases adoption of your API.
> Add pkg-config file

- CMakeLists.txt
- README.md
- cmake/modules/FindQt5Keychain.cmake
- cmake/modules/FindQtKeychain.cmake
- src/CMakeLists.txt
- src/o0keychainstore.cpp
- src/o0keychainstore.h
This pull request implements qtkeychain. I think this would generally be preferable over encryption through obfuscation. You will have to test this on your end to make sure this works. I will probably test if this works on my own end but I would like to make this available for review.
https://github.com/frankosterfeld/qtkeychain
> 
> - Mac OS X: Passwords are stored in the OS X Keychain.
> 
> - Linux/Unix: If running, GNOME Keyring is used, otherwise qtkeychain tries to use KWallet (via D-Bus), if available.
> 
> - Windows: By default, the Windows Credential Store is used (requires Windows 7 or newer). Pass -DUSE_CREDENTIAL_STORE=OFF to cmake use disable it. If disabled, QtKeychain uses the Windows API function CryptProtectData to encrypt the password with the user's logon credentials. …
> added keychain store

- examples/implicit_redirect.html
- src/o1.cpp
- src/o1.h
- src/o2.cpp
- src/o2.h
- src/o2replyserver.cpp
- src/o2replyserver.h
Adds three features to `o2`:
* **External QNetworkAccessManager support for authenticator** - useful for applications that already have a `QNetworkAccessManager`, or custom subclass of one, and where additional state may exist, e.g. proxy settings or extended authorization support.
* **Add extra request parameters support to O2 authenticator** - useful for passing OAuth2 vendor-specific key/value URL pairs, e.g. custom key names which may be necessary for connections, but non-standard OAuth2 pairs.
* **Add support for implicit grant flow completed by Javascript**
- When user-agent receives the #query response, use Javascript to forward the URL fragment on to the local redirect server as a query parameter string (example HTML provided).
- This flow requires a timer that fires …
> O2 Monsanto Company features

- src/o2gft.cpp
- src/o2google.h
- src/src.pri
If you download the current sources and try to build, you will end up with multiple build errors.
This change:
- add 2 missing include
- add the missing o2google in src.pri
> Fix broken build caused by O2Google

- src/o2gft.cpp
There are 3 unused constants in o2gft.cpp causing some warnings.
> Remove unused constants causing warnings

- src/o1.cpp
Replace qSort by std::sort to fix deprecated warnings
> qSort is deprecated - use std::sort #87

- src/o2.cpp
In the O2::onRefreshFinished() callback, the new access token is saved as expected. However O2::onRefreshFinished() assumes that the authorization server will provide the refresh token in the response. If the authorization server does not provide a refresh token, the old refresh token is replaced by an empty string. This issue is easily reproducible with YouTube where the access token expires each hour.
According to the OAuth v2 specs, when generating a new access token using a refresh token, the authorization server is not required to return the old refresh token nor a new refresh token. See https://tools.ietf.org/html/draft-ietf-oauth-v2-31
Also YouTube explicitly tells that the response when refreshing an access token DOES NOT contain the refresh token ( …
> Fix for #103: Refresh token is deleted when generating a new access token

- src/o2uber.cpp
The const O2_OAUTH2_GRANT_TYPE_UBER_CODE is unused and causes a warning depending on your build settings.
> Remove unused const O2_OAUTH2_GRANT_TYPE_UBER_CODE to avoid warnings.

- src/o2requestor.cpp
- src/o2requestor.h
Some OAuth 2 services require the access token to be sent as a Authentication HTTP header. This is the case for Twitch and Mixer which require respectively an 'OAuth' and 'Bearer' header for OAuth 2.
For those special cases, O2Requestor fails when retrying because the Authentication HTTP header is not updated with the new access token: when the access token expires and is refreshed, O2Requestor::retry() needs to update the Authentication HTTP header. In order to do so, O2Requestor needs to know the format of the Authentication HTTP header.
This change adds an optional property 'accessTokenInAuthenticationHTTPHeaderFormat_' to O2Requestor to make it work which those services.
> O2Requestor retry() fails for OAuth 2 services requiring access token to be sent as a Authentication HTTP header

- src/o2requestor.cpp
We have seen some crashes in O2Requestor::onRequestFinished(). When the sender() is cast to QNetworkReply*, the pointer is not checked and this can led to a NULL dereference when calling senderReply->error().
The fix consists of performing the safety checks in the same order as O2Requestor::onRequestError(). The pointer dereference occurs only after  reply_ == senderReply which should prevent the crash.
> Prevent crash in O2Requestor::onRequestFinished()

- src/o2requestor.cpp
- src/o2requestor.h
Some services (for example Mixer and Twitch) require the access token to be sent as a Authentication HTTP header and refuse requests with the access token in the query.
The function setAccessTokenInQueryFormat() allows to use or ignore the access token in the query. The default value of `%1` means that the query will contain the access token. By setting the value to an empty string, the query will not contain the access token.
> Add possibility to not use the access token in the query

- src/o0globals.h
- src/o2requestor.cpp
- src/o2requestor.h
Some services like Mixer have PATCH requests. O2 is currently unable to perform those.  The new function customRequest() allows you to create such custom requests.
> Add support for custom requests (PATCH for example)

- src/o2replyserver.cpp
error when building with clang 7
note: call 'std::move' explicitly to avoid copying
see https://travis-ci.org/qgis/QGIS/jobs/439416330#L723
> fix local variable will be copied despite being returned by name

- src/o2.cpp
The response might contain access or refresh tokens that are considered
sensitive data.
> Don't print response in O2::onVerificationReceived()

- README.md
- src/CMakeLists.txt
- src/o0baseauth.cpp
- src/o0baseauth.h
- src/o0globals.h
- src/o0jsonresponse.cpp
- src/o0jsonresponse.h
- src/o2.cpp
- src/o2.h
- src/o2googledevice.cpp
- src/o2googledevice.h
- src/o2pollserver.cpp
- src/o2pollserver.h
Google employs a dialect of RFC8628 for their "Google Sign-In for TVs and Devices". Some constants are different, but the main grant flow is the same.
This is what Google does different from RFC8628 (that I've found):
* Google sets the grant type to `http://oauth.net/grant_type/device/1.0` whereas RFC8628 defines it as `urn:ietf:params:oauth:grant-type:device_code`
* Google uses `verification_url` instead of `*_uri` in their _Device Authorization Response_.
* Google uses various HTTP response codes for e.g. `authorization_pending`, `slow_down`, and other errors in their _Device Access Token Response_ whilst RFC8628 says the HTTP response code should always be `400`.
> Add support for RFC8628 and Google Sign-In for TVs and Devices

- o2.pc.cmake
- src/src.pri
Two minor changes:
* Added o2googledevice.{cpp,h} to _src.pri_
* Set the linker flags in _o2.pc.cmake_ to `-lo2` instead of `@CMAKE_LIBRARY_PATH@`. In fact, `@CMAKE_LIBRARY_PATH@` would produce a "Semicolon-separated list of directories..." which is not what is wanted.
> Build system fixes

- src/o0jsonresponse.cpp
- src/o2pollserver.h
My embedded board toolchain is ancient (gcc-4.5.3) and failed to build o2 without these fixes
> Minor fixes for old toolchains

- src/o2pollserver.cpp
Two changes:
* `QNetworkReply::error()` will return `NoError` even when there was an HTTP error response code. This change make sure that the error field of the json response is always checked for "authorization_pending" or "slow_down".
* Don't start polling right away. Nobody's that fast on their phone to approve the device before the first poll request.
> Fix pollserver

- src/o2googledevice.cpp
- src/o2googledevice.h
Since O2GoogleDevice now no longer have anything in common with
O2Google, change parent class to O2.
> Update URLs used for O2GoogleDevice

- src/o2requestor.cpp
- src/o2requestor.h
Same as #143 for the `finished()` signal that includes the reply headers.
> also add an errorText parameter to the finished() signal with headers
